### ISSUE TITLE
テキストの段落

### ISSUE THREAD

**Issue by takahiro-nakayama** [satomi-ya/Training_2#5]
https://github.com/satomi-ya/Training_2/blob/900c575c96562ee91bf431d8d9b1d29f318f36b4/index.html#L59-L61

上記テキストは全てで段落となるので
```html
<p>Post videos with your skills, Like and follow others to be more popular.</p>
```
とし、必要に応じて`<br>`を挿入してください。

**Comment by satomi-ya** [comment]
section3 section4も同様に修正しました。

**Comment by takahiro-nakayama** [comment]
確認しました！
